---
baseURL: https://resume.yuslife.cc
languageCode: zh-tw
title: 余承翰 Hank Yu
module:
  imports:
  - path: github.com/chenghanxyu/toha/v4
  mounts:
  - source: "./node_modules/flag-icon-css/flags"
    target: static/flags
  - source: "./node_modules/@fontsource/mulish/files"
    target: static/files
  - source: "./node_modules/katex/dist/fonts"
    target: static/fonts
languages:
  zh:
    languageName: 中文
    weight: "1"
  en:
    languageName: English
    weight: "2"
DefaultContentLanguage: zh
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: "2"
    endLevel: "6"
    ordered: false
outputs:
  home:
  - HTML
  - RSS
  - JSON
enableEmoji: true
params:
  background: "/images/site/background.jpg"
  logo:
    main: "/images/site/main-logo.png"
    inverted: "/images/site/inverted-logo.png"
    favicon: "/images/site/favicon.png"
  gitRepo: https://github.com/chenghanxyu/hugo-toha.github.io
  gitBranch: main
  topNavbar:
    maxVisibleSections: "5"
  features:
    darkMode:
      enable: true
      services:
        darkreader:
          defaultColorScheme: system
          fixes:
            invert:
            - img[src$=".svg"]
          theme:
            brightness: "100"
            contrast: "100"
            sepia: "0"
    portfolio:
      enable: true
    blog:
      enable: false
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
    notes:
      enable: false
    comment:
      enable: false
      services:
        disqus:
          shortName: toha-example-site
    analytics:
      enabled: true
      services:
        google:
          id: G-YKW7BNEX9Q
    support:
      enable: false
      services:
        kofi:
          user: hossainemruz
          text: Tip Me
          textColor: "#f9fafc"
          backgroundColor: "#248aaa"
    toc:
      enable: true
    tags:
      enable: false
    flags:
      enable: true
      flagOverwrites:
      - languageCode: en
        countryCode: us
      - languageCode: zh-tw
        countryCode: tw
    embedpdf:
      enable: false
    flowchart:
      enable: false
      services:
        mermaid: 
    math:
      enable: false
      services:
        katex:
          delimiters:
          - left: "$$"
            right: "$$"
            display: true
          - left: "\\\\["
            right: "\\\\]"
            display: true
          - left: "$"
            right: "$"
            display: false
          - left: "\\\\("
            right: "\\\\)"
            display: false
    syntaxHighlight:
      enable: true
      services:
        hljs:
          noHighlightRe: "/^no-highlight$/i"
    videoPlayer:
      enable: true
      services:
        plyr: 
  footer:
    enable: true
    template: footer.html
    navigation:
      enable: true
      customMenus: true
    contactMe:
      enable: true
    credentials:
      enable: true
    newsletter:
      enable: false
      provider: mailchimp
      mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e
    disclaimer:
      enable: false
