---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.yaml
  label: 全域設定
- type: directory
  path: data/zh-tw
  label: 中文版
  create: all
  match: "**/*"
- type: directory
  path: data/en
  label: 英文版
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.109.0
  - NODE_VERSION=v18.12.1
  - NPM_VERSION=8.19.2
  - HUGO_ENV=production
  - HUGO_ENABLEGITINFO=true
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
